### ISSUE TITLE
babel 7 support

### ISSUE THREAD

**Issue by jeysal** [jeysal/babel-plugin-spock#8]
Babel 7 support would also enable us to get rid of the duplicate `babel-core` dependency and to stop using both scoped and regular babel packages, taking some complexity out of plugin development.

Currently blocked by https://github.com/power-assert-js/babel-plugin-espower/pull/23.

**Comment by twada** [comment]
FYI: [babel-plugin-espower v3.0.0-beta.1: The first beta version of Babel7 support (2017-12-25)](https://github.com/power-assert-js/babel-plugin-espower/releases/tag/v3.0.0-beta.1)

**Comment by jeysal** [comment]
Thanks a lot for notifying me!
I'll look into updating the dependency soon-ish.
